// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waqlfxfdtsmldibinuaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcWxmeGZkdHNtbGRpYmludWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNTM5NDMsImV4cCI6MjA0OTgyOTk0M30.8oGijDNWLDG1MjEiI8tWMqF810NzAhCQNlNAYAMbFkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);